### ISSUE TITLE
Fix 404s on reload

### ISSUE THREAD

**Issue by ethanfrey** [confio/code-explorer#2]
Currently (with github pages), reloading the app leads to a 404.

For example, try to enter https://confio.github.io/code-explorer/codes/2
You can however go to https://confio.github.io/code-explorer/ and then click on the second code.

I had the same issue in name-app and used HashRouter which is a wee bit uglier but works.

Suggestion of HashRouter: https://stackoverflow.com/a/46060999

Other is to use a custom 404 page with some magic redirecting javascript: https://www.pluralsight.com/guides/deploying-cra-to-github-pages-using-react-router

**Comment by webmaster128** [comment]
Arg, this you don't realize when using the explorer from the start page only.

I don't like the workaround, at it adds too much indirection for nice URL which we don't really need. So until gh-pages get's a native fallback feature, I'll go with the HashRouter.

**Comment by webmaster128** [comment]
Here we go: https://confio.github.io/code-explorer/#/contracts/cosmos1ym5m5dw7pttft5w430nxx6uat8f84ck4algmhg

I implemented a router type setting, so more sophisticated deployments can easily change back to BrowserRouter.
